kind: Deployment
apiVersion: apps/v1
metadata:
  name: test01-fdevsec
spec:
  template:
    metadata:
      labels:
        app: test01-fdevsec
    spec:
      containers:
      - name: test01-fdevsec
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/test01-fdevsec:latest
  selector:
    matchLabels:
      app: test01-fdevsec
---
kind: Service
apiVersion: v1
metadata:
  name: test01-fdevsec
spec:
  type: LoadBalancer
  selector:
    app: test01-fdevsec
  ports:
  - name: http
    port: 5006
    targetPort: 3006
